### ISSUE TITLE
Doesn't build on windows 10

### ISSUE THREAD

**Issue by w01fgang** [reklatsmasters/node-process-list#11]
Build fails with 
```
..\src\win\tasklist.cpp(17): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory [C:\Users\I\Documents\habitinstaller\leaf\node_modules\process-list\build\processlist.vcxproj]
  win_delay_load_hook.cc
```

**Comment by reklatsmasters** [comment]
Unfortunately, i can't repeat this issue in my windows 10. This file is the part of Microsoft ATL (Active Template Library).
The main problem is skipping prebuild version 😞

**Comment by w01fgang** [comment]
I try to build it on the fresh installation with `python` and `node-gyp` installed.
For sure I need `.Net Framework` or something that contains missing headers.

Or maybe you can create a prebuilded binary with [node-pre-gyp](https://github.com/mapbox/node-pre-gyp)?

**Comment by reklatsmasters** [comment]
@w01fgang This module already used prebuilded binaries. Which version of nodejs are you using?

**Comment by w01fgang** [comment]
@reklatsmasters Thanks for the speedy reply!
I tried with 9.3.0 and 8.9.3

**Comment by reklatsmasters** [comment]
@w01fgang It's a bug in prebuild/prebuild-install#15. There are 2 fixes:

* install Microsoft ATL (Active Template Library) as I said above
* use this module as dependecy from npm, see couchbase/couchnode#74

**Comment by w01fgang** [comment]
I'll try it! Thanks!
