### ISSUE TITLE
Upgrade dependency prebuild-install to support Custom binaries

### ISSUE THREAD

**Issue by bvamos** [reklatsmasters/node-process-list#32]
Hi,

I would like to use this package in an environment where GitHub binaries are behind a mirror repository, what is supported by prebuild-install, but the version 4.0.0 has a bug.
This was fixed here:
https://github.com/prebuild/prebuild-install/commit/3c3cfeefb143977ca575c32177d61d274329ffe2

Can you upgrade prebuild-install to the latest version?

**Comment by reklatsmasters** [comment]
I hope, it resolved in v2.0.0
